import os
from datetime import datetime

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib import colors


def generate_report(founder_data):
    """
    Generate a FounderAI PDF report.
    Returns the relative report path.
    """

    os.makedirs("reports", exist_ok=True)

    report_name = (
        f"{founder_data.get('name','founder')}_"
        f"{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    )

    report_path = os.path.join(
        "reports",
        report_name
    )

    doc = SimpleDocTemplate(report_path)

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph(
            "<b><font size='22'>FoundrAI</font></b>",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "Founder Intelligence Report",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"<b>Founder:</b> {founder_data.get('name','Founder')}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d %B %Y %H:%M')}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    data = [

        ["Metric", "Value"],

        ["Founder Score", founder_data.get("score", 0)],

        ["Startup Stage", founder_data.get("startup_stage", "-")],

        ["Budget", f"₹{founder_data.get('budget',0)}"],

        ["Team Size", founder_data.get("team_size", 0)],

        ["Programming", founder_data.get("programming", 0)],

        ["Marketing", founder_data.get("marketing", 0)],

        ["Finance", founder_data.get("finance", 0)],

        ["Leadership", founder_data.get("leadership", 0)],

        ["Communication", founder_data.get("communication", 0)],

        ["Problem Solving", founder_data.get("problem_solving", 0)],

        ["Risk Tolerance", founder_data.get("risk_tolerance", 0)]

    ]

    table = Table(
        data,
        colWidths=[200, 220]
    )

    table.setStyle(
        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

        ])
    )

    story.append(table)

    story.append(Spacer(1, 25))

    story.append(
        Paragraph(
            "<b>AI Founder Advice</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            founder_data.get(
                "ai_advice",
                "No AI recommendation available."
            ),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Generated by FoundrAI Founder Operating System</b>",
            styles["Italic"]
        )
    )

    doc.build(story)

    return report_path